server:
  port: 8082
application:
  name: basic-project
  version: 1.0.0
  base-url:
    context: /${application.name}/${application.version}

springdoc:
  swagger-ui:
    #path: /user-manage-system/1.0.0/swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false

logging:
  level:
    org:
      springframework:
        web: INFO
        hibernate: ERROR
    com: INFO
    root: INFO
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){yellow} %clr(:){red} %clr(%m){faint}%n"
    file: "%d{yy-MM-dd E HH:mm:ss.SSS } [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:\Users\ASUS\OneDrive\Documents\logs\${application.name}\${application.version}\elk-stack.log


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    health:
      show-details: always
  metrics:
    tags:
      application: ${application.name}




